set -g default-terminal "xterm-ghostty"
set -ga terminal-overrides ",xterm-ghostty:Tc"

set -g window-style 'fg=default,bg=default'
set -g window-active-style 'fg=default,bg=default'

set -g pane-border-style "fg=white"
set -g pane-active-border-style "fg=cyan,bg=default"

set -g status-style "bg=cyan,fg=black"
set -g message-style "bg=cyan,fg=black"
set -g message-command-style "bg=cyan,fg=black"

set -g mouse on
set-window-option -g mode-style "bg=cyan,fg=black"

unbind C-b
set-option -g prefix C-m
bind-key C-m send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind '"'
unbind %
unbind w
bind w new-window
bind W choose-window
bind t split-window -h
bind T split-window -v

set -g extended-keys on
set -g extended-keys-format csi-u
